---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-front-config
data:
   URL_GET: "http://get-srv:8081"
   URL_POST: "http://post-srv:8082"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front
      labels:
        app: front
    spec:
      containers:
      - image: dimeder13/frontend:latest
        envFrom:
        - configMapRef:
            name: env-front-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        name: front
---
apiVersion: v1
kind: Service
metadata:
  name: front-srv
  labels:
    app: front
spec:
  type: NodePort
  ports:
  - nodePort: 32080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front 
