apiVersion: v1
kind: ConfigMap
metadata:
  name: post-conf
  namespace: demo
data:
  POSTPORT: "8082"
  BACKPORT: "8083"
  BACKADDR: "back-srv"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  namespace: demo
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      name: post
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: nigth/postconv
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: post-conf
---
apiVersion: v1
kind: Service
metadata:
  name: post-srv
  namespace: demo
  labels:
    app: post
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: post

